ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at VARCHAR(64) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_by_user_id BIGINT UNSIGNED NULL;

CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (deleted_at);
