#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/root-env.sh"

BACKEND_ENV_FILE="$ROOT_DIR/backend/.env.production"
FRONTEND_ENV_FILE="$ROOT_DIR/dashboard/.env.production"
WORKER_PROD_ENV_FILE="$ROOT_DIR/backend/.worker.production.env"

if ! load_root_env "env-production"; then
  echo "[env-production] Missing root .env. Create it first: cp .env.example .env"
  exit 1
fi

copy_if_missing "$ROOT_DIR/backend/.env.production.example" "$BACKEND_ENV_FILE" "env-production"
copy_if_missing "$ROOT_DIR/dashboard/.env.production.example" "$FRONTEND_ENV_FILE" "env-production"
copy_if_missing "$ROOT_DIR/backend/.worker.production.env.example" "$WORKER_PROD_ENV_FILE" "env-production"

apply_env_mappings "env-production" "$BACKEND_ENV_FILE" \
  "PORT:BACKEND_PORT" \
  "SERVE_DASHBOARD:BACKEND_SERVE_DASHBOARD" \
  "FRONTEND_DIST_DIR:BACKEND_FRONTEND_DIST_DIR" \
  "SCHEDULER_ENABLED:BACKEND_SCHEDULER_ENABLED" \
  "SCHEDULER_INTERVAL_MS:BACKEND_SCHEDULER_INTERVAL_MS" \
  "DB_HOST:BACKEND_DB_HOST" \
  "DB_PORT:BACKEND_DB_PORT" \
  "DB_USER:BACKEND_DB_USER" \
  "DB_PASSWORD:BACKEND_DB_PASSWORD" \
  "DB_NAME:BACKEND_DB_NAME" \
  "DB_CONNECTION_LIMIT:BACKEND_DB_CONNECTION_LIMIT" \
  "JWT_SECRET:BACKEND_JWT_SECRET" \
  "MQTT_WS_URL:BACKEND_MQTT_WS_URL" \
  "MQTT_USERNAME:BACKEND_MQTT_USERNAME" \
  "MQTT_PASSWORD:BACKEND_MQTT_PASSWORD" \
  "MQTT_CLIENT_ID_PREFIX:BACKEND_MQTT_CLIENT_ID_PREFIX" \
  "JWT_ACCESS_TTL_SEC:BACKEND_JWT_ACCESS_TTL_SEC" \
  "JWT_REFRESH_TTL_SEC:BACKEND_JWT_REFRESH_TTL_SEC" \
  "COOKIE_SECURE:BACKEND_COOKIE_SECURE" \
  "COOKIE_SAME_SITE:BACKEND_COOKIE_SAME_SITE" \
  "COOKIE_DOMAIN:BACKEND_COOKIE_DOMAIN" \
  "CORS_ORIGINS:BACKEND_CORS_ORIGINS" \
  "AUTH_LOGIN_RATE_LIMIT_MAX:BACKEND_AUTH_LOGIN_RATE_LIMIT_MAX" \
  "AUTH_LOGIN_RATE_LIMIT_WINDOW_SEC:BACKEND_AUTH_LOGIN_RATE_LIMIT_WINDOW_SEC" \
  "COMMAND_EXECUTE_RATE_LIMIT_MAX:BACKEND_COMMAND_EXECUTE_RATE_LIMIT_MAX" \
  "COMMAND_EXECUTE_RATE_LIMIT_WINDOW_SEC:BACKEND_COMMAND_EXECUTE_RATE_LIMIT_WINDOW_SEC" \
  "SEED_ADMIN_EMAIL:BACKEND_SEED_ADMIN_EMAIL" \
  "SEED_ADMIN_PASSWORD:BACKEND_SEED_ADMIN_PASSWORD" \
  "SEED_SAMPLE_DEVICE_ID:BACKEND_SEED_SAMPLE_DEVICE_ID" \
  "SEED_SAMPLE_DEVICE_NAME:BACKEND_SEED_SAMPLE_DEVICE_NAME" \
  "SEED_SAMPLE_DEVICE_LOCATION:BACKEND_SEED_SAMPLE_DEVICE_LOCATION" \
  "SEED_DEMO_API_KEY:BACKEND_SEED_DEMO_API_KEY"

apply_env_mappings "env-production" "$FRONTEND_ENV_FILE" \
  "VITE_API_BASE_URL:FRONTEND_VITE_API_BASE_URL"

apply_env_mappings "env-production" "$WORKER_PROD_ENV_FILE" \
  "JWT_SECRET:BACKEND_JWT_SECRET" \
  "MQTT_WS_URL:BACKEND_MQTT_WS_URL" \
  "MQTT_USERNAME:BACKEND_MQTT_USERNAME" \
  "MQTT_PASSWORD:BACKEND_MQTT_PASSWORD" \
  "MQTT_CLIENT_ID_PREFIX:BACKEND_MQTT_CLIENT_ID_PREFIX" \
  "JWT_ACCESS_TTL_SEC:BACKEND_JWT_ACCESS_TTL_SEC" \
  "JWT_REFRESH_TTL_SEC:BACKEND_JWT_REFRESH_TTL_SEC" \
  "COOKIE_SECURE:BACKEND_COOKIE_SECURE" \
  "COOKIE_SAME_SITE:BACKEND_COOKIE_SAME_SITE" \
  "COOKIE_DOMAIN:BACKEND_COOKIE_DOMAIN" \
  "CORS_ORIGINS:BACKEND_CORS_ORIGINS" \
  "AUTH_LOGIN_RATE_LIMIT_MAX:BACKEND_AUTH_LOGIN_RATE_LIMIT_MAX" \
  "AUTH_LOGIN_RATE_LIMIT_WINDOW_SEC:BACKEND_AUTH_LOGIN_RATE_LIMIT_WINDOW_SEC" \
  "COMMAND_EXECUTE_RATE_LIMIT_MAX:BACKEND_COMMAND_EXECUTE_RATE_LIMIT_MAX" \
  "COMMAND_EXECUTE_RATE_LIMIT_WINDOW_SEC:BACKEND_COMMAND_EXECUTE_RATE_LIMIT_WINDOW_SEC" \
  "SEED_ADMIN_EMAIL:BACKEND_SEED_ADMIN_EMAIL" \
  "SEED_ADMIN_PASSWORD:BACKEND_SEED_ADMIN_PASSWORD" \
  "SEED_SAMPLE_DEVICE_ID:BACKEND_SEED_SAMPLE_DEVICE_ID"

echo "[env-production] Done."
